name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]*'

jobs:
  call-workflow:
    uses: codenautas/.github/.github/workflows/npm-publish.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
